
[build]
  command = "npx @11ty/eleventy"
  publish = "_site"

# Protect members for logged-in roles when Identity is enabled
[[redirects]]
  from = "/members/*"
  to = "/members/index.html"
  status = 200
  conditions = { Role = ["subscriber", "admin"] }

# Redirect unauthenticated visitors to paywall
[[redirects]]
  from = "/members/*"
  to = "/paywall/"
  status = 302
