name: Unpack site zip
on:
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Unzip archive
        run: |
          unzip -o pockettrainer_clean_site.zip -d .
          rm -f pockettrainer_clean_site.zip
      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          add: "."
          message: "Unpacked site zip"
